---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-oneagent-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: oneagent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dynatrace-oneagent-operator
      dynatrace: operator
      operator: oneagent
  template:
    metadata:
      labels:
        name: dynatrace-oneagent-operator
        dynatrace: operator
        operator: oneagent
    spec:
      containers:
        - name: dynatrace-oneagent-operator
          image: quay.io/dynatrace/dynatrace-oneagent-operator:latest
          command:
          - dynatrace-oneagent-operator
          imagePullPolicy: Always
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
